version: "3"
services:
  app:
    build:
      context: .
      dockerfile: backend_compose_dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./data/duke:/annotator_gui_backend/data/duke
